language: java

jdk:
- oraclejdk8

deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
  app:
    master: api-beer
  on:
    branch: master

after_success:
- COVERALL_REPO_TOKEN=$COVERALLS_REPO_TOKEN ./gradlew build test jacocoTestReport coveralls

after_failure:
- ./gradlew clean check --debug