language: java

jdk:
- oraclejdk8

deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
  on:
    branch: master

after_success:
- ./gradlew build jacocoTestReport

after_failure:
- ./gradlew clean check --debug