server:
  port: ${PORT:8080}

beer:
  datasource:
    jdbc-url: jdbc:postgres://stampy.db.elephantsql.com:5432/gkqdesjz
    username: gkqdesjz
    password: 0H60i2VQcIP3B5kXsyJvHGCQJkViiknd
    maximum-pool-size: 30
    driver-class-name: org.postgresql.Driver

spring:
  application:
    name: beer
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
  hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl

  cache:
      type: redis
  redis:
      host: redis-15960.c17.us-east-1-4.ec2.cloud.redislabs.com
      port: 15960
      password: uF8XwKNYZ7G71pxwEvvOvX1yl8wER72e




