server:
  port: ${PORT:8080}

spring:
  cache:
    type: redis
  redis:
    host: redis-15960.c17.us-east-1-4.ec2.cloud.redislabs.com
    port: 15960
    password: uF8XwKNYZ7G71pxwEvvOvX1yl8wER72e




