server:
  port: ${PORT:8080}

spring:
  application:
    name: beer
  data:
    mongodb:
      uri: mongodb://beer:beer123@ds213612.mlab.com:13612/beerdb

spotify:
  authentication:
    clientid: 03c20df0a9ff48cabdc1f1963774066d
    clientsecret: 9c0b4ca781364c78a8c7766194b99675
    redirecturi: http://localhost:8080/callback